baseURL: 'http://localhost:1313/'
title: "AWSD"
languageCode: "fr-FR"
theme: "TailBliss"
DefaultContentLanguage: fr
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
canonifyURLs: false
pagination:
  pagerSize: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true
postCSS:
  disable: true
