baseURL: "http://localhost/"
title: "AWSD"
theme: "PaperMod"
languageCode: "fr-FR"          # utile pour RSS/SEO (tu peux laisser fr-FR)
defaultContentLanguage: fr      # << clé qui pilote .Site.Language.Lang

languages:
  fr:
    languageName: "Français"
    weight: 1

pagination:
  disableAliases: false
  pagerSize: 10
  path: page

permalinks:
  posts: "/blog/:year/:slug/"
  projets: "/projets/:slug/"

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home: ["HTML", "RSS", "JSON"]
