baseURL: "http://localhost/"
languageCode: "fr-fr"
title: "AWSD"
theme: "PaperMod"

pagination:
  disableAliases: false
  pagerSize: 10
  path: page

permalinks:
  posts: "/blog/:year/:slug/"
  projets: "/projets/:slug/"

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home: ["HTML", "RSS", "JSON"]
