baseURL: "http://localhost/"
title: "AWSD — Artisan Web Software & Defense"
theme: "PaperMod"
languageCode: "fr-FR"
defaultContentLanguage: fr
enableRobotsTXT: true
canonifyURLs: true

languages:
  fr:
    languageName: "Français"
    weight: 1

pagination:
  disableAliases: false
  pagerSize: 9
  path: page

permalinks:
  posts: "/blog/:year/:slug/"
  projets: "/projets/:slug/"

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]

# Minification & post-process
minify:
  disableXML: true
  tdewolff:
    html:
      keepWhitespace: false

# Contrôle qualité images (Hugo imaging)
imaging:
  quality: 80
  resampleFilter: lanczos
