baseURL: "http://localhost/"
title: "AWSD"
theme: "PaperMod"
languageCode: "fr-FR"
defaultContentLanguage: fr

languages:
  fr:
    languageName: "Français"
    weight: 1

pagination:
  disableAliases: false
  pagerSize: 10
  path: page

permalinks:
  posts: "/blog/:year/:slug/"
  projets: "/projets/:slug/"

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home:    [HTML, RSS, JSON]
  section: [HTML, RSS]
