baseURL = 'http://localhost/'
title = "AWSD"
theme = "TailBliss"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = false
enableInlineShortcodes = false

[pagination]
  pagerSize = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.fr]
    locale = "fr-FR"
    label = "Français"
    weight = 1
    title = "AWSD"

  [languages.en]
    locale = "en-US"
    label = "English"
    weight = 2
    title = "AWSD"
