main:
  - name: "Qui suis-je ?"
    url: "/about-me/"
    layout: single
    weight: 1
  - name: "Portfolio"
    url: "/projets/"
    weight: 2
  - name: "Blog"
    url: "/blog/"
    weight: 3
  - name: "Contact"
    url: "/contact/"
    weight: 4