main:
  - name: "Blog"
    url: "/blog/"
    weight: 1
  - name: "Portfolio"
    url: "/projets/"
    weight: 2
  - name: "À propos"
    url: "/a-propos/"
    weight: 3
  - name: "Contact"
    url: "/contact/"
    weight: 4