ShowBreadCrumbs: true
ShowPostNavLinks: true
ShowReadingTime: true
ShowCodeCopyButtons: true
Showtoc: true
TocOpen: true

hideSummary: false
ShowRssButtonInSectionTermList: true
ShowPageNums: true

DisableSpecial1stPost: true
mainSections: ["blog"]

profileMode:
  enabled: true
  title: "Jean‑Vivien Sicot"
  subtitle: "Développeur web — Portfolio & Journal technique"
  imageUrl: "/images/avatar.jpg"
  imageWidth: 250
  imageHeight: 300
  buttons:
    - { name: "Portfolio", url: "/projets/" }
    - { name: "Blog", url: "/blog/" }
